# Generated by Django 4.2.27 on 2026-01-23 09:12
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_dob'),
    ]
    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
    ]